[package]
name = "particle_life_3d"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
eframe = { version = "0.21.3", features = ["wgpu"] }
encase = { version = "0.5.0", features = ["cgmath"] }
rand = "0.8.5"
rayon = "1.7.0"
